### ISSUE TITLE
Create sample data for sample map

### ISSUE THREAD

**Issue by MysterAitch** [kaya3/js3dgame#1]

**Comment by MysterAitch** [comment]
![20191102_162844](https://user-images.githubusercontent.com/1537214/68073988-ea9ec300-fd8d-11e9-8150-f29847c1f067.jpg)

**Comment by HaithamHmahmoud** [comment]
[js3dgame-master.zip](https://github.com/kaya3/js3dgame/files/3800707/js3dgame-master.zip)
